=== betsegawlemma/simgrid/src/surf/simgrid.dtd
<!-- Small DTD for SURF based tools. -->
<!ELEMENT platform ((include|trace|random|cluster|set|foreach|host|router|link|trace:connect)*,(include|route:multi|route|trace:connect|process)*)>
<!ATTLIST platform version CDATA "0.0">
<!ATTLIST platform xmlns:link CDATA "http://simgrid.gforge.inria.fr/">
<!ATTLIST platform xmlns:route CDATA "http://simgrid.gforge.inria.fr/">

<!ELEMENT include EMPTY>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT trace (#PCDATA)>
<!ATTLIST trace id CDATA #REQUIRED>
<!ATTLIST trace file CDATA "">
<!ATTLIST trace periodicity CDATA #REQUIRED>

<!ELEMENT random (prop*)>
<!ATTLIST random id CDATA #REQUIRED>
<!ATTLIST random min CDATA #REQUIRED>
<!ATTLIST random max CDATA #REQUIRED>
<!ATTLIST random mean CDATA #REQUIRED>
<!ATTLIST random std_deviation CDATA #REQUIRED>
<!ATTLIST random generator (DRAND48|RAND) "DRAND48">

<!ELEMENT trace:connect EMPTY>
<!ATTLIST trace:connect kind (HOST_AVAIL|POWER|LINK_AVAIL|BANDWIDTH|LATENCY) "HOST_AVAIL">
<!ATTLIST trace:connect trace CDATA #REQUIRED>
<!ATTLIST trace:connect element CDATA #REQUIRED>

<!ELEMENT set EMPTY>
<!ATTLIST set id CDATA #REQUIRED>
<!ATTLIST set prefix CDATA #REQUIRED>
<!ATTLIST set suffix CDATA #REQUIRED>
<!ATTLIST set radical CDATA #REQUIRED>

<!ELEMENT foreach (host|(host,link)|link)>
<!ATTLIST foreach set_id CDATA #REQUIRED>

<!ELEMENT host (prop*)>
<!ATTLIST host id CDATA #REQUIRED>
<!ATTLIST host power CDATA #REQUIRED>
<!ATTLIST host availability CDATA "1.0">
<!ATTLIST host availability_file CDATA "">
<!ATTLIST host state (ON|OFF) "ON">
<!ATTLIST host state_file CDATA "">
<!ATTLIST host interference_send CDATA "1.0">
<!ATTLIST host interference_recv CDATA "1.0">
<!ATTLIST host interference_send_recv CDATA "1.0">
<!ATTLIST host max_outgoing_rate CDATA "-1.0">
<!ATTLIST host vivaldi  CDATA "0 0 0">

<!ELEMENT prop EMPTY>
<!ATTLIST prop id CDATA #REQUIRED>
<!ATTLIST prop value CDATA #REQUIRED>

<!ELEMENT cluster EMPTY>
<!ATTLIST cluster id CDATA #REQUIRED>
<!ATTLIST cluster prefix CDATA #REQUIRED>
<!ATTLIST cluster suffix CDATA #REQUIRED>
<!ATTLIST cluster radical CDATA #REQUIRED>
<!ATTLIST cluster power CDATA #REQUIRED>
<!ATTLIST cluster bw CDATA #REQUIRED>
<!ATTLIST cluster lat CDATA #REQUIRED>
<!ATTLIST cluster bb_bw CDATA #REQUIRED>
<!ATTLIST cluster bb_lat CDATA #REQUIRED>

<!ELEMENT router EMPTY>
<!ATTLIST router id CDATA #REQUIRED>

<!ELEMENT link (prop*)>
<!ATTLIST link id CDATA #REQUIRED>
<!ATTLIST link bandwidth CDATA  #REQUIRED>
<!ATTLIST link bandwidth_file CDATA "">
<!ATTLIST link latency CDATA "0.0">
<!ATTLIST link latency_file CDATA "">
<!ATTLIST link state (ON|OFF) "ON">
<!ATTLIST link state_file CDATA "">
<!ATTLIST link sharing_policy (SHARED|FATPIPE) "SHARED">

<!ELEMENT route:multi (link:ctn+)>
<!ATTLIST route:multi src CDATA #REQUIRED>
<!ATTLIST route:multi dst CDATA #REQUIRED>
<!ATTLIST route:multi action (POSTPEND|PREPEND|OVERRIDE) "POSTPEND">
<!ATTLIST route:multi symmetric (YES|NO) "YES">

<!ELEMENT route (link:ctn*)>
<!ATTLIST route src CDATA #REQUIRED>
<!ATTLIST route dst CDATA #REQUIRED>
<!ATTLIST route impact_on_src CDATA "0.0">
<!ATTLIST route impact_on_dst CDATA "0.0">
<!ATTLIST route impact_on_src_with_other_recv CDATA "0.0">
<!ATTLIST route impact_on_dst_with_other_send CDATA "0.0">
<!ATTLIST route action (POSTPEND|PREPEND|OVERRIDE) "POSTPEND">

<!ELEMENT link:ctn EMPTY>
<!ATTLIST link:ctn id CDATA #REQUIRED>

<!ELEMENT process ((argument|prop)*)>
<!ATTLIST process host CDATA #REQUIRED>
<!ATTLIST process function CDATA #REQUIRED>
<!ATTLIST process start_time CDATA "-1.0">
<!ATTLIST process kill_time CDATA "-1.0">

<!ELEMENT argument EMPTY>
<!ATTLIST argument value CDATA #REQUIRED>

=== betsegawlemma/simgrid/teshsuite/simdag/platforms/one_cluster_foreach.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="2">
  <set id="myCluster" prefix="bob" suffix=".hamburger.edu"
       radical="0,2-4,6"/>

  <foreach set_id="myCluster">
    <host id="$1" power="1000000000"/>
    <link id="$1" bandwidth="125000000" latency="5E-5"/>
  </foreach>

  <link id="bob_backbone" bandwidth="2250000000" latency="5E-4"
	sharing_policy="FATPIPE"/>
 
  <route:multi src="myCluster" dst="myCluster" symmetric="NO">
    <link:ctn id="$src"/>
    <link:ctn id="bob_backbone"/>
    <link:ctn id="$dst"/>
  </route:multi>
</platform>

=== betsegawlemma/simgrid/examples/gras/mutual_exclusion/simple_token/simple_token.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="3">

 <process host="Tremblay" function="node">
  <argument value="4000"/>                           <!-- port on which I am listening -->
  <argument value="Fafard"/><argument value="4000"/> <!-- peer (successor) host id and port-->
  <argument value="--create-token"/>                 <!-- I'm first client, ie I have to create the token -->
 </process>
 
 <process host="Fafard" function="node">
  <argument value="4000"/>                           <!-- port on which I am listening -->
  <argument value="Jupiter"/><argument value="4000"/><!-- peer (successor) host id and port-->
 </process>
 
 <process host="Jupiter" function="node">
  <argument value="4000"/>                            <!-- port on which I am listening -->
  <argument value="Ginette"/><argument value="4000"/> <!-- peer (successor) host id and port-->
 </process>
 
 <process host="Ginette" function="node">
  <argument value="4000"/>                            <!-- port on which I am listening -->
  <argument value="Bourassa"/><argument value="4000"/><!-- peer (successor) host id and port-->
 </process>
 
 <process host="Bourassa" function="node">
  <argument value="4000"/>                            <!-- port on which I am listening -->
  <argument value="Tremblay"/><argument value="4000"/><!-- peer (successor) host id and port-->
 </process>
 
</platform>

=== betsegawlemma/simgrid/examples/java/app/masterworker/masterworker.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4">
  <process host="Jacquelin" function="app.masterworker.Master">
     <argument value="5"/>     <!-- Amount of tasks to dispatch -->
     <argument value="50000"/> <!-- Computation size of each task -->
     <argument value="10"/>    <!-- Communication size of each one -->
     <argument value="7"/>     <!-- Amount of workers waiting for orders -->
  </process>

  <process host="iRMX" function="app.masterworker.Worker">      <argument value="0"/>  <!-- Input mailbox --> </process>
  <process host="Bousquet" function="app.masterworker.Worker">  <argument value="1"/>  <!-- Input mailbox --> </process>
  <process host="Soucy" function="app.masterworker.Worker">     <argument value="2"/>  <!-- Input mailbox --> </process>
  <process host="Kuenning" function="app.masterworker.Worker">  <argument value="3"/>  <!-- Input mailbox --> </process>
  <process host="Browne" function="app.masterworker.Worker">    <argument value="4"/>  <!-- Input mailbox --> </process>
  <process host="Stephen" function="app.masterworker.Worker">   <argument value="5"/>  <!-- Input mailbox --> </process>
  <process host="Robert" function="app.masterworker.Worker">    <argument value="6"/>  <!-- Input mailbox --> </process>
</platform>

=== betsegawlemma/simgrid/examples/msg/gtnets/medium_tiers-d.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="2">

  <process host="Boucherville" function="master">
      <argument value="100"/>
      <argument value="Boyer"/>
      <argument value="1"/>
  </process>

  <process host="Forget" function="master">
      <argument value="100"/>
      <argument value="Yolande"/>
      <argument value="2"/>
  </process>

  <process host="Boyer" function="slave">
      <argument value="1"/>
  </process>

  <process host="Yolande" function="slave">
      <argument value="2"/>
  </process>

</platform>

=== betsegawlemma/simgrid/examples/java/comm_time/comm_time_deployment.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="2">
  <process host="Jacquelin" function="Master">
     <argument value="5000"/>  <!-- Amount of tasks to dispatch -->
     <argument value="50000"/> <!-- Computation size of each task -->
     <argument value="10"/>    <!-- Communication size of each one -->
     <argument value="21"/>    <!-- Amount of slaves waiting for orders -->
  </process>
  
  <process host="iRMX" function="Slave">
     <argument value="0"/>  <!-- Input mailbox -->
  </process>
  
  <process host="Bousquet" function="Slave">
     <argument value="1"/></process>
  <process host="Soucy" function="Slave">
     <argument value="2"/></process>
  <process host="Casavant" function="Slave">
     <argument value="3"/></process>
  <process host="Jackson" function="Slave">
     <argument value="4"/></process>
  <process host="Geoff" function="Slave">
     <argument value="5"/></process>
  <process host="Disney" function="Slave">
     <argument value="6"/></process>
  <process host="McGee" function="Slave">
     <argument value="7"/></process>
  <process host="Gatien" function="Slave">
     <argument value="8"/></process>
  <process host="Laroche" function="Slave">
     <argument value="9"/></process>
  <process host="Tanguay" function="Slave">
     <argument value="10"/></process>
  <process host="Morin" function="Slave">
     <argument value="11"/></process>
  <process host="Ethernet" function="Slave">
     <argument value="12"/></process>
  <process host="Bellemarre" function="Slave">
     <argument value="13"/></process>
  <process host="Harry" function="Slave">
     <argument value="14"/></process>
  <process host="Olivier" function="Slave">
     <argument value="15"/></process>
  <process host="Boucherville" function="Slave">
     <argument value="16"/></process>
  <process host="Pointe_Claire" function="Slave">
     <argument value="17"/></process>
  <process host="Kansas" function="Slave">
     <argument value="18"/></process>
  <process host="King" function="Slave">
     <argument value="19"/></process>
  <process host="Lapointe" function="Slave">
     <argument value="20"/></process>
</platform>

=== betsegawlemma/simgrid/teshsuite/simdag/partask/platform_2p_1sl.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="2">


  <host id="cpu0" power="1"/>
  <host id="cpu1" power="1"/>
  <link id="link0" bandwidth="1" latency=".5" sharing_policy="SHARED"/>
  <route src="cpu0" dst="cpu1">
    <link:ctn id="link0"/>
  </route>
  <route src="cpu1" dst="cpu0">
    <link:ctn id="link0"/>
  </route>
</platform>

=== betsegawlemma/simgrid/examples/platforms/deployment_remote_io.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
  <process host="alice" function="host">
    <argument value = "c:\Windows\setupact.log"/>
  </process>
  <process host="bob" function="host">
    <argument value = "/scratch/lib/libsimgrid.so.3.6.2"/>
  </process>
  <process host="carl" function="host">
    <argument value = "/scratch/lib/libsimgrid.so.3.6.2"/>
  </process>
  <process host="dave" function="host">
    <argument value = "c:\Windows\bootstat.dat"/>
  </process>
</platform>

=== betsegawlemma/simgrid/examples/msg/trace/test11.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">

<platform version="2">

<trace id="1" periodicity="10">
0  0.5
10  0.5
20  1.00
30  0.5
40  0.5
50  0.5
60  0.5
</trace>

<host id="CPU1" power="20"/>
<trace:connect kind="POWER" trace="1" element="CPU1"/>
<process host="CPU1" function="test_trace">
<argument value="420"/>
<argument value="2.0"/>
</process>
<process host="CPU1" function="test_trace">
<argument value="310"/>
<argument value="1.0"/>
</process>
<process host="CPU1" function="test_trace" start_time="50">
<argument value="990"/>
<argument value="9.0"/>
</process>

</platform>
