=== betsegawlemma/simgrid/src/surf/simgrid.dtd
<!-- Small DTD for SURF based tools. -->
<!ELEMENT platform ((include|trace|random|cluster|set|foreach|host|router|link|trace:connect)*,(include|route:multi|route|trace:connect|process)*)>
<!ATTLIST platform version CDATA "0.0">
<!ATTLIST platform xmlns:link CDATA "http://simgrid.gforge.inria.fr/">
<!ATTLIST platform xmlns:route CDATA "http://simgrid.gforge.inria.fr/">

<!ELEMENT include EMPTY>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT trace (#PCDATA)>
<!ATTLIST trace id CDATA #REQUIRED>
<!ATTLIST trace file CDATA "">
<!ATTLIST trace periodicity CDATA #REQUIRED>

<!ELEMENT random (prop*)>
<!ATTLIST random id CDATA #REQUIRED>
<!ATTLIST random min CDATA #REQUIRED>
<!ATTLIST random max CDATA #REQUIRED>
<!ATTLIST random mean CDATA #REQUIRED>
<!ATTLIST random std_deviation CDATA #REQUIRED>
<!ATTLIST random generator (DRAND48|RAND) "DRAND48">

<!ELEMENT trace:connect EMPTY>
<!ATTLIST trace:connect kind (HOST_AVAIL|POWER|LINK_AVAIL|BANDWIDTH|LATENCY) "HOST_AVAIL">
<!ATTLIST trace:connect trace CDATA #REQUIRED>
<!ATTLIST trace:connect element CDATA #REQUIRED>

<!ELEMENT set EMPTY>
<!ATTLIST set id CDATA #REQUIRED>
<!ATTLIST set prefix CDATA #REQUIRED>
<!ATTLIST set suffix CDATA #REQUIRED>
<!ATTLIST set radical CDATA #REQUIRED>

<!ELEMENT foreach (host|(host,link)|link)>
<!ATTLIST foreach set_id CDATA #REQUIRED>

<!ELEMENT host (prop*)>
<!ATTLIST host id CDATA #REQUIRED>
<!ATTLIST host power CDATA #REQUIRED>
<!ATTLIST host availability CDATA "1.0">
<!ATTLIST host availability_file CDATA "">
<!ATTLIST host state (ON|OFF) "ON">
<!ATTLIST host state_file CDATA "">
<!ATTLIST host interference_send CDATA "1.0">
<!ATTLIST host interference_recv CDATA "1.0">
<!ATTLIST host interference_send_recv CDATA "1.0">
<!ATTLIST host max_outgoing_rate CDATA "-1.0">
<!ATTLIST host vivaldi  CDATA "0 0 0">

<!ELEMENT prop EMPTY>
<!ATTLIST prop id CDATA #REQUIRED>
<!ATTLIST prop value CDATA #REQUIRED>

<!ELEMENT cluster EMPTY>
<!ATTLIST cluster id CDATA #REQUIRED>
<!ATTLIST cluster prefix CDATA #REQUIRED>
<!ATTLIST cluster suffix CDATA #REQUIRED>
<!ATTLIST cluster radical CDATA #REQUIRED>
<!ATTLIST cluster power CDATA #REQUIRED>
<!ATTLIST cluster bw CDATA #REQUIRED>
<!ATTLIST cluster lat CDATA #REQUIRED>
<!ATTLIST cluster bb_bw CDATA #REQUIRED>
<!ATTLIST cluster bb_lat CDATA #REQUIRED>

<!ELEMENT router EMPTY>
<!ATTLIST router id CDATA #REQUIRED>

<!ELEMENT link (prop*)>
<!ATTLIST link id CDATA #REQUIRED>
<!ATTLIST link bandwidth CDATA  #REQUIRED>
<!ATTLIST link bandwidth_file CDATA "">
<!ATTLIST link latency CDATA "0.0">
<!ATTLIST link latency_file CDATA "">
<!ATTLIST link state (ON|OFF) "ON">
<!ATTLIST link state_file CDATA "">
<!ATTLIST link sharing_policy (SHARED|FATPIPE) "SHARED">

<!ELEMENT route:multi (link:ctn+)>
<!ATTLIST route:multi src CDATA #REQUIRED>
<!ATTLIST route:multi dst CDATA #REQUIRED>
<!ATTLIST route:multi action (POSTPEND|PREPEND|OVERRIDE) "POSTPEND">
<!ATTLIST route:multi symmetric (YES|NO) "YES">

<!ELEMENT route (link:ctn*)>
<!ATTLIST route src CDATA #REQUIRED>
<!ATTLIST route dst CDATA #REQUIRED>
<!ATTLIST route impact_on_src CDATA "0.0">
<!ATTLIST route impact_on_dst CDATA "0.0">
<!ATTLIST route impact_on_src_with_other_recv CDATA "0.0">
<!ATTLIST route impact_on_dst_with_other_send CDATA "0.0">
<!ATTLIST route action (POSTPEND|PREPEND|OVERRIDE) "POSTPEND">

<!ELEMENT link:ctn EMPTY>
<!ATTLIST link:ctn id CDATA #REQUIRED>

<!ELEMENT process ((argument|prop)*)>
<!ATTLIST process host CDATA #REQUIRED>
<!ATTLIST process function CDATA #REQUIRED>
<!ATTLIST process start_time CDATA "-1.0">
<!ATTLIST process kill_time CDATA "-1.0">

<!ELEMENT argument EMPTY>
<!ATTLIST argument value CDATA #REQUIRED>

=== betsegawlemma/simgrid/teshsuite/simdag/platforms/three_hosts_non_symmetric_route.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="2">
  <host id="bob" power="1000000000"/>
  <host id="alice" power="500000000"/>
  <host id="trudy" power="250000000"/>

  <link id="link1" bandwidth="125000000" latency="5E-5"/>
  <link id="link2" bandwidth="125000000" latency="5E-5"/>
  <link id="link3" bandwidth="125000000" latency="5E-5"/>

  <route src="bob" dst="alice">
    <link:ctn id="link1"/>
  </route>
  <route src="alice" dst="bob">
    <link:ctn id="link2"/>
    <link:ctn id="link3"/>
  </route>

  <route src="bob" dst="trudy">
    <link:ctn id="link2"/>
  </route>

  <route src="trudy" dst="bob">
    <link:ctn id="link2"/>
  </route>

  <route src="trudy" dst="alice">
    <link:ctn id="link3"/>
  </route>
  <route src="alice" dst="trudy">
    <link:ctn id="link3"/>
  </route>
</platform>

=== betsegawlemma/simgrid/examples/java/dht/chord/chord.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4">
  <process host="Gatien" function="dht.chord.Node">
    <argument value="48"/>        <!-- my id -->
    <argument value="1"/>         <!-- known id -->
    <argument value="400"/>        <!-- time to sleep before it starts-->
    <argument value ="600"/>    <!-- deadline -->
  </process>
  <process host="McGee" function="dht.chord.Node">
    <argument value="42"/>        <!-- my id -->
    <argument value="1"/>         <!-- known id -->
    <argument value="300"/>        <!-- time to sleep before it starts-->
    <argument value ="600"/>    <!-- deadline -->
  </process>
  <process host="iRMX" function="dht.chord.Node">
    <argument value="38"/>        <!-- my id -->
    <argument value="1"/>         <!-- known id -->
    <argument value="200"/>         <!-- time to sleep before it starts-->
    <argument value ="600"/>    <!-- deadline -->
  </process>
  <process host="Geoff" function="dht.chord.Node">
    <argument value="32"/>        <!-- my id -->
    <argument value="1"/>         <!-- known id -->
    <argument value="100"/>         <!-- time to sleep before it starts-->
    <argument value ="600"/>    <!-- deadline -->
  </process>
  <process host="TeX" function="dht.chord.Node">
    <argument value="21"/>        <!-- my id -->
    <argument value="1"/>         <!-- known id -->
    <argument value="40"/>        <!-- time to sleep before it starts-->
    <argument value ="600"/>    <!-- deadline -->
  </process>
  <process host="Jean_Yves" function="dht.chord.Node">
    <argument value="14"/>        <!-- my id -->
    <argument value="1"/>         <!-- known id -->
    <argument value="16"/>        <!-- time to sleep before it starts-->
    <argument value ="600"/>    <!-- deadline -->
  </process>
  <process host="Boivin" function="dht.chord.Node">
    <argument value="8"/>         <!-- my id -->
    <argument value="1"/>         <!-- known id -->
    <argument value="1"/>         <!-- time to sleep before it starts-->
    <argument value ="600"/>    <!-- deadline -->
  </process>
  <process host="Jacquelin" function="dht.chord.Node">
    <argument value="1"/>         <!-- my id -->
    <argument value ="600"/>    <!-- deadline -->
  </process>
</platform>

=== betsegawlemma/simgrid/examples/msg/icomms/small_platform.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "simgrid.dtd">
 <platform version="2">
 <AS  id="AS0"  routing="Full">
   <!-- ljlkj -->
   <host id="Tremblay" power="98095000"/>
   <host id="Ruby" power="98095000"/>
   <host id="Perl" power="98095000"/>
   <host id="Java" power="98095000"/>
   <link id="1" bandwidth="498000000" latency="0.00015" sharing_policy="FATPIPE"/>
   <link id="2" bandwidth="498000000" latency="0.00015" sharing_policy="FATPIPE"/>
   <link id="3" bandwidth="498000000" latency="0.00015" sharing_policy="FATPIPE"/>
   <route src="Tremblay" dst="Ruby"><link:ctn id="1"/></route>
   <route src="Ruby" dst="Tremblay"><link:ctn id="1"/></route>
   <route src="Tremblay" dst="Perl"><link:ctn id="2"/></route>
   <route src="Perl" dst="Tremblay"><link:ctn id="2"/></route>
   <route src="Tremblay" dst="Java"><link:ctn id="3"/></route>
   <route src="Java" dst="Tremblay"><link:ctn id="3"/></route>
 </AS>
 </platform>

=== betsegawlemma/simgrid/examples/msg/trace/test10.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="2">
  <host id="CPU1" power="20" availability_file="trace/file.trace"/>
  <process host="CPU1" function="test_trace">
  	<argument value="420"/>
  	<argument value="2.0"/>
  </process>
  <process host="CPU1" function="test_trace">
  	<argument value="310"/>
  	<argument value="1.0"/>
  </process>
  <process host="CPU1" function="test_trace" start_time="50">
  	<argument value="990"/>
  	<argument value="9.0"/>
  </process>
</platform>

=== betsegawlemma/simgrid/examples/msg/ns3/onelink-d.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">

  <process host="S1" function="master">
      <argument value="100"/>
      <argument value="C1"/>
      <argument value="1"/>
  </process>

  <process host="C1" function="slave">
    <argument value="1"/>
  </process>

  <process host="S2" function="master">
      <argument value="1000"/>
      <argument value="C2"/>
      <argument value="2"/>
  </process>
  
  <process host="C2" function="slave">
    <argument value="2"/>
  </process>
   
   
    <process host="S3" function="master">
      <argument value="2000"/>
      <argument value="C3"/>
      <argument value="3"/>
  </process>
  
  <process host="C3" function="slave">
    <argument value="3"/>
  </process>
     
</platform>

=== betsegawlemma/simgrid/examples/msg/parallel_task/test_ptask_platform.xml
<?xml version='1.0'?>
 <!DOCTYPE platform SYSTEM "simgrid.dtd">
 <platform version="2">
 <AS  id="AS0"  routing="Full">
   <!-- ljlkj -->
   <host id="Tremblay" power="1e9"/>
   <host id="Jupiter" power="1e9"/>
   <host id="Fafard" power="1e9"/>
   <host id="Ginette" power="1e9"/>
   <link id="0" bandwidth="1e8" latency="100e-6"/>
   <link id="1" bandwidth="1e8" latency="100e-6"/>
   <link id="2" bandwidth="1e8" latency="100e-6"/>
   <link id="3" bandwidth="1e8" latency="100e-6"/>
   <link id="switch" bandwidth="1e8" latency="100e-6" sharing_policy="FATPIPE"/>
   <link id="loopback" bandwidth="1e10" latency="1e-6" sharing_policy="FATPIPE"/>
   <route src="Tremblay" dst="Tremblay"><link:ctn id="loopback"/></route>
   <route src="Jupiter" dst="Jupiter"><link:ctn id="loopback"/></route>
   <route src="Fafard" dst="Fafard"><link:ctn id="loopback"/></route>
   <route src="Ginette" dst="Ginette"><link:ctn id="loopback"/></route>
   <route src="Tremblay" dst="Jupiter">
     <link:ctn id="0"/><link:ctn id="switch"/><link:ctn id="1"/>
   </route>
   <route src="Tremblay" dst="Fafard">
     <link:ctn id="0"/><link:ctn id="switch"/><link:ctn id="2"/>
   </route>
   <route src="Tremblay" dst="Ginette">
     <link:ctn id="0"/><link:ctn id="switch"/><link:ctn id="3"/>
   </route>
   <route src="Jupiter" dst="Tremblay">
     <link:ctn id="1"/><link:ctn id="switch"/><link:ctn id="0"/>
   </route>
   <route src="Jupiter" dst="Fafard">
     <link:ctn id="1"/><link:ctn id="switch"/><link:ctn id="2"/>
   </route>
   <route src="Jupiter" dst="Ginette">
     <link:ctn id="1"/><link:ctn id="switch"/><link:ctn id="3"/>
   </route>
   <route src="Fafard" dst="Tremblay">
     <link:ctn id="2"/><link:ctn id="switch"/><link:ctn id="0"/>
   </route>
   <route src="Fafard" dst="Jupiter">
     <link:ctn id="2"/><link:ctn id="switch"/><link:ctn id="1"/>
   </route>
   <route src="Fafard" dst="Ginette">
     <link:ctn id="2"/><link:ctn id="switch"/><link:ctn id="3"/>
   </route>
   <route src="Ginette" dst="Tremblay">
     <link:ctn id="3"/><link:ctn id="switch"/><link:ctn id="0"/>
   </route>
   <route src="Ginette" dst="Jupiter">
     <link:ctn id="3"/><link:ctn id="switch"/><link:ctn id="1"/>
   </route>
   <route src="Ginette" dst="Fafard">
     <link:ctn id="3"/><link:ctn id="switch"/><link:ctn id="2"/>
   </route>
 </AS>
 </platform>

=== betsegawlemma/simgrid/link_energy/simple_cluster.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4.1">
<AS id="AS0" routing="Full">
  <host id="H-0" speed="1Gf"/>
  <host id="H-1" speed="1Gf"/>
  <host id="H-2" speed="1Gf"/>
  <host id="H-3" speed="1Gf"/>
  <host id="H-4" speed="1Gf"/>
  <router id="H-acme_router"/>
  <link id="acme_link_0" bandwidth="1GBps" latency="10ms"><prop id="watt_range" value="10.3581:10.7479"/></link>
  <link id="acme_link_1" bandwidth="1GBps" latency="10ms"><prop id="watt_range" value="10.3581:10.7479"/></link>
  <link id="acme_link_2" bandwidth="1GBps" latency="10ms"><prop id="watt_range" value="10.3581:10.7479"/></link>
  <link id="acme_link_3" bandwidth="1GBps" latency="10ms"><prop id="watt_range" value="10.3581:10.7479"/></link>
  <link id="acme_link_4" bandwidth="1GBps" latency="10ms"><prop id="watt_range" value="10.3581:10.7479"/></link>
  <route src="H-0" dst="H-1">
  <link_ctn id="acme_link_0"/>
  </route>
  <route src="H-1" dst="H-acme_router">
  <link_ctn id="acme_link_1"/>
  </route>
  <route src="H-acme_router" dst="H-2">
  <link_ctn id="acme_link_2"/>
  </route>
  <route src="H-2" dst="H-3">
  <link_ctn id="acme_link_3"/>
  </route>
</AS>
</platform>

=== betsegawlemma/simgrid/examples/msg/energy-link/energy_consumption_0L_p.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4.1">
	<AS id="AS0" routing="Full">
		<host id="SRC" speed="100.0Mf,50.0Mf,20.0Mf" pstate="0">
			<prop id="watt_per_state" value="100.0:120.0:200.0, 93.0:110.0:170.0, 90.0:105.0:150.0" />
			<prop id="watt_off" value="0" />
		</host>
		<host id="DST" speed="100.0Mf,50.0Mf,20.0Mf" pstate="0">
			<prop id="watt_per_state" value="100.0:120.0:200.0, 93.0:110.0:170.0, 90.0:105.0:150.0" />
		</host>
		<link id="L1" bandwidth="50Mbps" latency="10ms">
			<prop id="watt_range" value="10.3581:10.7479" />
		</link>
		<route src="SRC" dst="DST">
			<link_ctn id="L1" />
		</route>
	</AS>
</platform>
