=== betsegawlemma/simgrid/src/surf/simgrid.dtd
<!-- Small DTD for SURF based tools. -->
<!ELEMENT platform ((include|trace|random|cluster|set|foreach|host|router|link|trace:connect)*,(include|route:multi|route|trace:connect|process)*)>
<!ATTLIST platform version CDATA "0.0">
<!ATTLIST platform xmlns:link CDATA "http://simgrid.gforge.inria.fr/">
<!ATTLIST platform xmlns:route CDATA "http://simgrid.gforge.inria.fr/">

<!ELEMENT include EMPTY>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT trace (#PCDATA)>
<!ATTLIST trace id CDATA #REQUIRED>
<!ATTLIST trace file CDATA "">
<!ATTLIST trace periodicity CDATA #REQUIRED>

<!ELEMENT random (prop*)>
<!ATTLIST random id CDATA #REQUIRED>
<!ATTLIST random min CDATA #REQUIRED>
<!ATTLIST random max CDATA #REQUIRED>
<!ATTLIST random mean CDATA #REQUIRED>
<!ATTLIST random std_deviation CDATA #REQUIRED>
<!ATTLIST random generator (DRAND48|RAND) "DRAND48">

<!ELEMENT trace:connect EMPTY>
<!ATTLIST trace:connect kind (HOST_AVAIL|POWER|LINK_AVAIL|BANDWIDTH|LATENCY) "HOST_AVAIL">
<!ATTLIST trace:connect trace CDATA #REQUIRED>
<!ATTLIST trace:connect element CDATA #REQUIRED>

<!ELEMENT set EMPTY>
<!ATTLIST set id CDATA #REQUIRED>
<!ATTLIST set prefix CDATA #REQUIRED>
<!ATTLIST set suffix CDATA #REQUIRED>
<!ATTLIST set radical CDATA #REQUIRED>

<!ELEMENT foreach (host|(host,link)|link)>
<!ATTLIST foreach set_id CDATA #REQUIRED>

<!ELEMENT host (prop*)>
<!ATTLIST host id CDATA #REQUIRED>
<!ATTLIST host power CDATA #REQUIRED>
<!ATTLIST host availability CDATA "1.0">
<!ATTLIST host availability_file CDATA "">
<!ATTLIST host state (ON|OFF) "ON">
<!ATTLIST host state_file CDATA "">
<!ATTLIST host interference_send CDATA "1.0">
<!ATTLIST host interference_recv CDATA "1.0">
<!ATTLIST host interference_send_recv CDATA "1.0">
<!ATTLIST host max_outgoing_rate CDATA "-1.0">
<!ATTLIST host vivaldi  CDATA "0 0 0">

<!ELEMENT prop EMPTY>
<!ATTLIST prop id CDATA #REQUIRED>
<!ATTLIST prop value CDATA #REQUIRED>

<!ELEMENT cluster EMPTY>
<!ATTLIST cluster id CDATA #REQUIRED>
<!ATTLIST cluster prefix CDATA #REQUIRED>
<!ATTLIST cluster suffix CDATA #REQUIRED>
<!ATTLIST cluster radical CDATA #REQUIRED>
<!ATTLIST cluster power CDATA #REQUIRED>
<!ATTLIST cluster bw CDATA #REQUIRED>
<!ATTLIST cluster lat CDATA #REQUIRED>
<!ATTLIST cluster bb_bw CDATA #REQUIRED>
<!ATTLIST cluster bb_lat CDATA #REQUIRED>

<!ELEMENT router EMPTY>
<!ATTLIST router id CDATA #REQUIRED>

<!ELEMENT link (prop*)>
<!ATTLIST link id CDATA #REQUIRED>
<!ATTLIST link bandwidth CDATA  #REQUIRED>
<!ATTLIST link bandwidth_file CDATA "">
<!ATTLIST link latency CDATA "0.0">
<!ATTLIST link latency_file CDATA "">
<!ATTLIST link state (ON|OFF) "ON">
<!ATTLIST link state_file CDATA "">
<!ATTLIST link sharing_policy (SHARED|FATPIPE) "SHARED">

<!ELEMENT route:multi (link:ctn+)>
<!ATTLIST route:multi src CDATA #REQUIRED>
<!ATTLIST route:multi dst CDATA #REQUIRED>
<!ATTLIST route:multi action (POSTPEND|PREPEND|OVERRIDE) "POSTPEND">
<!ATTLIST route:multi symmetric (YES|NO) "YES">

<!ELEMENT route (link:ctn*)>
<!ATTLIST route src CDATA #REQUIRED>
<!ATTLIST route dst CDATA #REQUIRED>
<!ATTLIST route impact_on_src CDATA "0.0">
<!ATTLIST route impact_on_dst CDATA "0.0">
<!ATTLIST route impact_on_src_with_other_recv CDATA "0.0">
<!ATTLIST route impact_on_dst_with_other_send CDATA "0.0">
<!ATTLIST route action (POSTPEND|PREPEND|OVERRIDE) "POSTPEND">

<!ELEMENT link:ctn EMPTY>
<!ATTLIST link:ctn id CDATA #REQUIRED>

<!ELEMENT process ((argument|prop)*)>
<!ATTLIST process host CDATA #REQUIRED>
<!ATTLIST process function CDATA #REQUIRED>
<!ATTLIST process start_time CDATA "-1.0">
<!ATTLIST process kill_time CDATA "-1.0">

<!ELEMENT argument EMPTY>
<!ATTLIST argument value CDATA #REQUIRED>

=== betsegawlemma/simgrid/examples/java/basic/basic_deployment.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="2">
  <process host="Jacquelin" function="Master">
     <argument value="5"/>     <!-- Amount of tasks to dispatch -->
     <argument value="50000"/> <!-- Computation size of each task -->
     <argument value="10"/>    <!-- Communication size of each one -->
     <argument value="7"/>     <!-- Amount of slaves waiting for orders -->
  </process>
  
  <process host="Jackson" function="Forwarder">
     <argument value="0"/>  <!-- Input mailbox -->
     <argument value="7"/>  <!-- First output mailbox -->
     <argument value="8"/>  <!-- Last output mailbox -->
  </process>
  <process host="Casavant" function="Forwarder">
     <argument value="1"/>  <!-- Input mailbox -->
     <argument value="9"/>  <!-- First output mailbox -->
     <argument value="10"/> <!-- Last output mailbox -->
  </process>
  
  <process host="iRMX" function="Slave">
     <argument value="2"/>  <!-- Input mailbox -->
  </process>
  <process host="Bousquet" function="Slave">
     <argument value="3"/>  <!-- Input mailbox -->
  </process>  
  <process host="Soucy" function="Slave">
     <argument value="4"/>  <!-- Input mailbox -->
  </process>  
  <process host="Kuenning" function="Slave">
     <argument value="5"/>  <!-- Input mailbox -->
  </process>  
  <process host="Browne" function="Slave">
     <argument value="6"/>  <!-- Input mailbox -->
  </process>  
  <process host="Stephen" function="Slave">
     <argument value="7"/>  <!-- Input mailbox -->
  </process>  
  <process host="Robert" function="Slave">
     <argument value="8"/>  <!-- Input mailbox -->
  </process>  
  <process host="Sirois" function="Slave">
     <argument value="9"/>  <!-- Input mailbox -->
  </process>  
  <process host="Monique" function="Slave">
     <argument value="10"/>  <!-- Input mailbox -->
  </process>  
</platform>

=== betsegawlemma/simgrid/examples/msg/mc/chord_liveness/deploy_chord_liveness.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">
 
  <process host="Jean_Yves" function="node">
    <argument value="14"/>        <!-- my id -->
    <argument value="1"/>         <!-- known id -->
    <argument value="400"/>        <!-- time to sleep before it starts-->
    <argument value ="600"/>		<!-- deadline -->
  </process>
  
  <process host="Boivin" function="node">
    <argument value="8"/>         <!-- my id -->
    <argument value="1"/>         <!-- known id -->
    <argument value="300"/>         <!-- time to sleep before it starts-->
    <argument value ="600"/>		<!-- deadline -->
  </process>

  <process host="Jacquelin" function="node">
    <argument value="1"/>         <!-- my id -->
    <argument value ="600"/>             <!-- deadline -->
  </process>

</platform>

=== betsegawlemma/simgrid/link-energy-test/s4u_energy-consumption_p.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid/simgrid.dtd">
<platform version="4">
  <AS id="AS0" routing="Full">
    <host id="Host0" speed="100.0Mf,50.0Mf,20.0Mf" pstate="0">
      <prop id="watt_per_state" value="100.0:120.0:200.0, 93.0:110.0:170.0, 90.0:105.0:150.0" />
      <prop id="watt_off" value="0" />
    </host>
    
    <host id="Host2" speed="100.0Mf,50.0Mf,20.0Mf" pstate="0">
      <prop id="watt_per_state" value="100.0:120.0:200.0, 93.0:110.0:170.0, 90.0:105.0:150.0" />
    </host>

    <link id="LINK_HOST0" bandwidth="1000MBps" latency="10ms">
      <prop id = "watts" value="10.3581:10.7479" />
    </link>
    
    <route src="Host0" dst="Host2">
      <link_ctn id="LINK_HOST0"/>
    </route>

  </AS>
</platform>

=== betsegawlemma/simgrid/src/bindings/ruby/quicksort_deployment.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="2">
  <process host="Inmos" function="Sender">
      <argument value ="Bellevue"/>
      <argument value="5000000"/>
      <argument value="100000"/>
      <argument value="Receiver"/> <!--will be used as a mailbox alias-->
  </process>
  <process host="Bellevue" function="Receiver">
  	  <argument value="Inmos"/>
 	  <argument value="Sender"/> <!--will be used as a mailbox alias-->
  </process>
</platform>

=== betsegawlemma/simgrid/examples/msg/gtnets/waxman5-p.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="2">
  <host id="Marc" power="214563000"/>
  <host id="Boivin" power="214563000"/>
  <host id="Emacs" power="214563000"/>
  <host id="Jackson" power="214563000"/>
  <host id="Inc" power="214563000"/>
  <link id="6" bandwidth="1475160.57655719" latency="0.442242015190778" />
  <link id="4" bandwidth="1388512.38295812" latency="0.416265540250451" />
  <link id="1" bandwidth="2248511.50079418" latency="0.674086789664358" />
  <link id="3" bandwidth="1890355.13925945" latency="0.566714213691522" />
  <link id="0" bandwidth="970350.508803584" latency="0.290903764155777" />
  <link id="2" bandwidth="1382762.99083586" latency="0.414541915854115" />
  <link id="5" bandwidth="35925.952527695" latency="0.010770329614269" />
  <route src="Marc" dst="Boivin"><link:ctn id="5"/>  </route>
  <route src="Marc" dst="Emacs"><link:ctn id="4"/>  </route>
  <route src="Marc" dst="Jackson"><link:ctn id="5"/><link:ctn id="6"/>  </route>
  <route src="Marc" dst="Inc"><link:ctn id="5"/><link:ctn id="0"/>  </route>
  <route src="Boivin" dst="Marc"><link:ctn id="5"/>  </route>
  <route src="Boivin" dst="Emacs"><link:ctn id="2"/>  </route>
  <route src="Boivin" dst="Jackson"><link:ctn id="6"/>  </route>
  <route src="Boivin" dst="Inc"><link:ctn id="0"/>  </route>
  <route src="Emacs" dst="Marc"><link:ctn id="4"/>  </route>
  <route src="Emacs" dst="Boivin"><link:ctn id="2"/>  </route>
  <route src="Emacs" dst="Jackson"><link:ctn id="3"/>  </route>
  <route src="Emacs" dst="Inc"><link:ctn id="3"/><link:ctn id="1"/>  </route>
  <route src="Jackson" dst="Marc"><link:ctn id="6"/><link:ctn id="5"/>  </route>
  <route src="Jackson" dst="Boivin"><link:ctn id="6"/>  </route>
  <route src="Jackson" dst="Emacs"><link:ctn id="3"/>  </route>
  <route src="Jackson" dst="Inc"><link:ctn id="1"/>  </route>
  <route src="Inc" dst="Marc"><link:ctn id="0"/><link:ctn id="5"/>  </route>
  <route src="Inc" dst="Boivin"><link:ctn id="0"/>  </route>
  <route src="Inc" dst="Emacs"><link:ctn id="1"/><link:ctn id="3"/>  </route>
  <route src="Inc" dst="Jackson"><link:ctn id="1"/>  </route>
</platform>

=== betsegawlemma/simgrid/examples/amok/saturate/saturate.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="2">

  <process host="Tremblay" function="sensor">  <argument value="Bourassa:4000"/> </process>
  <process host="Jupiter"  function="sensor">  <argument value="Bourassa:4000"/> </process>
  <process host="Fafard"   function="sensor">  <argument value="Bourassa:4000"/> </process>
  <process host="Ginette"  function="sensor">  <argument value="Bourassa:4000"/> </process>

  <process host="Bourassa" function="maestro"> <argument value="4000"/>          </process>

</platform>

=== betsegawlemma/simgrid/examples/platforms/routing_none.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">

<!--     This platform does not use any routing. 
         It is what Constant network model expects. -->
	 
<platform version="3">
  <AS id="AS0" routing="None">
    <host id="node-0.acme.org" power="1Gf"/>
    <host id="node-1.acme.org" power="1Gf"/>
    <host id="node-2.acme.org" power="1Gf"/>
    <host id="node-3.acme.org" power="1Gf"/>
    <host id="node-4.acme.org" power="1Gf"/>
    <host id="node-5.acme.org" power="1Gf"/>
    <host id="node-6.acme.org" power="1Gf"/>
    <host id="node-7.acme.org" power="1Gf"/>
    <host id="node-8.acme.org" power="1Gf"/>
    <host id="node-9.acme.org" power="1Gf"/>
  </AS>
</platform>

=== betsegawlemma/simgrid/examples/msg/trace/test7.xml
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "simgrid.dtd">
<platform version="3">
	  <AS  id="AS0"  routing="Full">
  <host id="CPU1" power="20" availability_file="trace/file.trace"/>  	
  </AS>

  <process host="CPU1" function="test_trace" start_time="10">
  	<argument value="400"/>
  	<argument value="1.5"/>
  </process>
  <process host="CPU1" function="test_trace" start_time="20">
  	<argument value="300"/>
  	<argument value="1.5"/>
  </process>
</platform>
