=== betsegawlemma/simgrid/src/surf/surfxml.dtd
<!-- Small DTD for SURF based tools. -->
<!ELEMENT platform_description ((include|host|router|link)*,(include|route|process)*)>
<!ATTLIST platform_description version CDATA "0.0">

<!ELEMENT include EMPTY>
<!ATTLIST include file CDATA #REQUIRED>

<!ELEMENT host (prop*)>
<!ATTLIST host id CDATA #REQUIRED>
<!ATTLIST host power CDATA #REQUIRED>
<!ATTLIST host availability CDATA "1.0">
<!ATTLIST host availability_file CDATA "">
<!ATTLIST host state (ON|OFF) "ON">
<!ATTLIST host state_file CDATA "">
<!ATTLIST host interference_send CDATA "1.0">
<!ATTLIST host interference_recv CDATA "1.0">
<!ATTLIST host interference_send_recv CDATA "1.0">
<!ATTLIST host max_outgoing_rate CDATA "-1.0">

<!ELEMENT prop EMPTY>
<!ATTLIST prop id CDATA #REQUIRED>
<!ATTLIST prop value CDATA #REQUIRED>

<!ELEMENT router EMPTY>
<!ATTLIST router id CDATA #REQUIRED>

<!ELEMENT link (prop*)>
<!ATTLIST link id CDATA #REQUIRED>
<!ATTLIST link bandwidth CDATA  #REQUIRED>
<!ATTLIST link bandwidth_file CDATA "">
<!ATTLIST link latency CDATA "0.0">
<!ATTLIST link latency_file CDATA "">
<!ATTLIST link state (ON|OFF) "ON">
<!ATTLIST link state_file CDATA "">
<!ATTLIST link sharing_policy (SHARED|FATPIPE) "SHARED">

<!ELEMENT route (link:ctn*)>
<!ATTLIST route src CDATA #REQUIRED>
<!ATTLIST route dst CDATA #REQUIRED>
<!ATTLIST route impact_on_src CDATA "0.0">
<!ATTLIST route impact_on_dst CDATA "0.0">
<!ATTLIST route impact_on_src_with_other_recv CDATA "0.0">
<!ATTLIST route impact_on_dst_with_other_send CDATA "0.0">

<!ELEMENT link:ctn EMPTY>
<!ATTLIST link:ctn id CDATA #REQUIRED>

<!ELEMENT process ((argument|prop)*)>
<!ATTLIST process host CDATA #REQUIRED>
<!ATTLIST process function CDATA #REQUIRED>
<!ATTLIST process start_time CDATA "-1.0">
<!ATTLIST process kill_time CDATA "-1.0">

<!ELEMENT argument EMPTY>
<!ATTLIST argument value CDATA #REQUIRED>

=== betsegawlemma/simgrid/examples/amok/saturate/saturate_deployment.xml
<?xml version='1.0'?>
<!DOCTYPE platform_description SYSTEM "surfxml.dtd">
<platform_description version="1">

  <process host="Tremblay" function="sensor">  <argument value="Bourassa:4000"/> </process>
  <process host="Jupiter"  function="sensor">  <argument value="Bourassa:4000"/> </process>
  <process host="Fafard"   function="sensor">  <argument value="Bourassa:4000"/> </process>
  <process host="Ginette"  function="sensor">  <argument value="Bourassa:4000"/> </process>

  <process host="Bourassa" function="maestro"> <argument value="4000"/>          </process>

</platform_description>

=== betsegawlemma/simgrid/examples/msg/msg_deployment.xml
<?xml version='1.0'?>
<!DOCTYPE platform_description SYSTEM "surfxml.dtd">
<platform_description version="1">
  <process host="Jacquelin" function="master">
     <argument value="20"/>
     <argument value="50000"/>
     <argument value="10"/>
     <argument value="iRMX"/>
     <argument value="Casavant"/>
     <argument value="Bousquet"/>
     <argument value="Soucy"/>
     <argument value="Jackson"/>
  </process>
  <process host="Jackson" function="forwarder">
     <argument value="Kuenning"/>
     <argument value="Browne"/> 
     <argument value="Stephen"/>
 </process>
  <process host="Casavant" function="forwarder">
     <argument value="Robert"/>
     <argument value="Sirois"/> 
     <argument value="Monique"/>
 </process>
  <process host="iRMX" function="slave"/>
  <process host="Bousquet" function="slave"/>
  <process host="Soucy" function="slave"/>
  <process host="Kuenning" function="slave"/>
  <process host="Browne" function="slave"/>
  <process host="Stephen" function="slave"/>
  <process host="Robert" function="slave"/>
  <process host="Sirois" function="slave"/>
  <process host="Monique" function="slave"/>
</platform_description>

=== betsegawlemma/simgrid/examples/msg/small_deployment.xml
<?xml version='1.0'?>
<!DOCTYPE platform_description SYSTEM "surfxml.dtd">
<platform_description>
  <!-- The master process (with some arguments) -->
  <process host="Tremblay" function="master">
     <argument value="20"/>       <!-- Number of tasks -->
     <argument value="50000"/>    <!-- Computation size of tasks -->
     <argument value="10"/>       <!-- Communication size of tasks -->
     <argument value="Jupiter"/>  <!-- First slave -->
     <argument value="Fafard"/>   <!-- Second slave -->
     <argument value="Ginette"/>  <!-- Third slave -->
     <argument value="Bourassa"/> <!-- Last slave -->
  </process>
  <!-- The slave process (with no argument) -->
  <process host="Jupiter" function="slave"/>
  <process host="Fafard" function="slave"/>
  <process host="Ginette" function="slave"/>
  <process host="Bourassa" function="slave"/>
</platform_description>

=== betsegawlemma/simgrid/doc/gtut-files/11-explicitwait.xml
<?xml version='1.0'?>
<!DOCTYPE platform_description SYSTEM "surfxml.dtd">
<platform_description version="1">
  <process host="Jacquelin" function="server">
    <argument value="12345"/>
  </process>
  <process host="Boivin" function="client">
    <argument value="Jacquelin"/>
    <argument value="12345"/>
  </process>
  <process host="Geoff" function="client">
    <argument value="Jacquelin"/>
    <argument value="12345"/>
  </process>
</platform_description>

=== betsegawlemma/simgrid/examples/msg/gtnets/dogbone-d.xml
<?xml version='1.0'?>
<!DOCTYPE platform_description SYSTEM "surfxml.dtd">
<platform_description version="1">

  <process host="S1" function="master">
      <argument value="100000000"/>
      <argument value="C1"/>
  </process>

  <process host="S2" function="master">
      <argument value="100000000"/>
      <argument value="C2"/>
  </process>

  <process host="C1" function="slave"/>
  <process host="C2" function="slave"/>

</platform_description>

=== betsegawlemma/simgrid/examples/gras/all2all/all2all_deployment.xml
<?xml version='1.0'?>
<!DOCTYPE platform_description SYSTEM "surfxml.dtd">
<platform_description>
  <!-- The Tremblay node, arguments :: all others nodes -->
  <process host="Tremblay" function="sender">
     <argument value="4000"/>
     <argument value="Jupiter"/>  
     <argument value="Fafard"/> 
     <argument value="Ginette"/> 
     <argument value="Bourassa"/> 
  </process>
  <!-- The Jupiter node, arguments :: all others nodes -->
  <process host="Jupiter" function="sender">
     <argument value="4000"/>
     <argument value="Tremblay"/> 
     <argument value="Fafard"/> 
     <argument value="Ginette"/> 
     <argument value="Bourassa"/> 
  </process>
  <!-- The Fafard node, arguments :: all others nodes -->
  <process host="Fafard" function="sender">
     <argument value="4000"/>
     <argument value="Tremblay"/> 
     <argument value="Jupiter"/>  
     <argument value="Ginette"/> 
     <argument value="Bourassa"/> 
  </process>
  <!-- The Ginette node, arguments :: all others nodes -->
  <process host="Ginette" function="sender">
     <argument value="4000"/>
     <argument value="Tremblay"/> 
     <argument value="Jupiter"/>  
     <argument value="Fafard"/> 
     <argument value="Bourassa"/> 
  </process>
  <!-- The Bourassa node, arguments :: all others nodes -->
  <process host="Bourassa" function="sender">
     <argument value="4000"/>
     <argument value="Tremblay"/> 
     <argument value="Jupiter"/>  
     <argument value="Fafard"/> 
     <argument value="Ginette"/> 
  </process>
  
  
  <process host="Tremblay" function="receiver">
     <argument value="4000"/>
     <argument value="4"/>  
  </process>
  <process host="Jupiter" function="receiver">
     <argument value="4000"/>
     <argument value="4"/>
  </process>
  <process host="Fafard" function="receiver">
     <argument value="4000"/>
     <argument value="4"/> 
  </process>
  <process host="Ginette" function="receiver">
     <argument value="4000"/>
     <argument value="4"/>
  </process>
  <process host="Bourassa" function="receiver">
     <argument value="4000"/>
     <argument value="4"/>
  </process>
</platform_description>
